name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Determine next version
      id: semver
      run: |
        # Fetch all tags
        git fetch --tags

        # Get the latest tag
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "0.0.0")
        echo "Latest tag: $latest_tag"

        # Extract the version numbers
        IFS='.' read -r -a version_parts <<< "$latest_tag"
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}

        # Increment the patch version
        new_patch=$((patch + 1))
        new_version="$major.$minor.$new_patch"

        echo "New version: $new_version"
        echo "::set-output name=version::$new_version"

    - name: Update project version
      run: |
        new_version=${{ steps.semver.outputs.version }}
        mvn versions:set -DnewVersion=$new_version
        mvn versions:commit

    - name: Create new tag
      run: |
        new_version=${{ steps.semver.outputs.version }}
        git tag $new_version
        git push origin $new_version

    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.version }}
        release_name: Release ${{ steps.semver.outputs.version }}
        body: |
          Changes in this release:
          $(git log -1 --pretty=%B)
        draft: false
        prerelease: false

