name: 'Migrate database schema'

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.SUPABASE_PASS }}
          POSTGRES_USER: ${{ secrets.SUPABASE_USER }}
          POSTGRES_DB: ${{ secrets.SUPABASE_DB }}
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.SUPABASE_URL }}
          user: ${{ secrets.SUPABASE_USER }}
          password: ${{ secrets.SUPABASE_PASS }}
          locations: filesystem:./src/main/resources/db.migration
      - run: echo 'deploying to prod'
