name: 'Migrate database schema'

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-latest
    env:
      SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
      SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
      SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
    steps:
      - uses: actions/checkout@v2
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/src/main/resources/db.migration:/flyway/sql:ro
          flyway/flyway:10.10.0-alpine
          -url="jdbc:postgresql://${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}?sslmode=require&user="${{ secrets.SUPABASE_USER }}&password=${{ secrets.SUPABASE_PASS }}"
          migrate
